version: '3'

services:

  app:
    build: .
    entrypoint: ./.docker/entrypoint.sh
    container_name: desafio05-github-ci
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3000:3000